### ISSUE TITLE
Why RCON web has to be disabled in Rust?

### ISSUE THREAD

**Issue by MatteoInfi** [gorcon/rcon#2]
I am trying to make this work with Rust game and I get `i/o timeout`. However I saw in the README that RCON web needs to be disabled. I would like to know why and if is possible to keep it enabled and send commands at the same time.
Thanks

**Comment by outdead** [comment]
Web rcon uses websockets. They are not supported in this implementation. And this support will not be here. Perhaps it will be added in that application https://github.com/gorcon/rcon-cli/issues/8

**Comment by HTMLGuyLLC** [comment]
Just seeing this thread. Will close my issue.
