### ISSUE TITLE
Getting connection timed out

### ISSUE THREAD

**Issue by HTMLGuyLLC** [gorcon/rcon#6]
I can connect using Rcon.io so I know the server/port is right and accessible.

The specific error (with server and port obfuscated):
`rcon: rcon: read packet size: read tcp {server}:{port}->{server}:{port}: i/o timeout`

I'll keep looking but figured I'd throw up an issue and see if you were aware of any causes for this.

**Comment by xllifi** [comment]
how did you solve this?
